### ISSUE TITLE
Use babel-plugin-lodash.

### ISSUE THREAD

**Issue by jdalton** [cape-io/lodash-humps#1]
You can use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) so you can write

``` js
import { camelCase, forEach, isArray, isObject, isString, map } from 'lodash'
```

instead of their individual long forms.

**Comment by webmasterkai** [comment]
Oh yeah baby, that's some nice stuff right there! Trying it out now.

**Comment by jdalton** [comment]
:metal: If you want to take it up a notch check out [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin).
