### ISSUE TITLE
More easily consumable to commonjs projects.

### ISSUE THREAD

**Issue by jdalton** [cape-io/lodash-humps#2]
You might dig, [babel-plugin-add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports#why) to make your module more easily consumable to traditional commonjs Node code. The `babel-plugin-add-module-exports` is basically [babel/scripts/add-module-exports.js](https://github.com/babel/babel/blob/master/scripts/add-module-exports.js).

**Comment by webmasterkai** [comment]
Yes! Thanks @jdalton!

I can't even begin to describe how awesome you are.
